<?php

return [
    'auto_triggers',
    'automation2s',
    'bounce_logs',
    'campaign_headers',
    'campaign_links',
    'campaign_webhooks',
    'campaigns',
    'campaigns_lists_segments',
    'click_logs',
    // 'customers',
    'email_links',
    'email_webhooks',
    'emails',
    'feedback_logs',
    'field_options',
    'fields',
    'forms',
    'mail_lists',
    'mail_lists_sending_servers',
    'open_logs',
    'pages',
    'segment_conditions',
    'segments',
    'senders',
    'sending_domains',
    'signatures',
    'subscribers',
    'timelines',
    'tracking_domains',
    'tracking_logs',
    'trigger_sessions',
    'unsubscribe_logs',
    'websites',
];
